inp_file: anytown_map.inp
output_path: output
iterations: 10
network_topology_type: complex
plcs: !include anytown_plcs.yaml

simulator: epynet
demand: pdd

#use_control_agent: True
agent_config_file: agent_config.yaml

# batch_simulations: 2
# log_level: debug

# mininet_cli: True

